#集群的终极方案
server:
    port: 8761
spring:
    application:
        name: eureka-server  # 应用名称 不要使用特殊字符
    security:
        user:
            name: root
            password: 123456
eureka:
    server:
        peer-node-read-timeout-ms: 1000
    client:
        service-url:
            defaultZone: "https://root:123456@spring-cloud.ghj.zone/eureka/server/eureka,\
                https://root:123456@spring-cloud.ghjv22.tk/eureka/server/eureka"
    instance: # 实例的配置
        instance-id: ${INSTANCE_NAME:${spring.application.name}}:${server.port}   # 主机名称 : 应用名称 : 端口号
        prefer-ip-address: true # 以ip的形式显示具体的服务信息
        lease-renewal-interval-in-seconds: 5  # 服务实例的续约的时间间隔