server:
    port: 8081
spring:
    application:
        name: login-service
eureka:
    client:
        service-url:
            defaultZone: "https://root:123456@spring-cloud.ghj.zone/eureka/server/eureka,\
                https://root:123456@spring-cloud.ghjv22.tk/eureka/server/eureka"
